apiVersion: apps/v1
kind: Deployment
metadata:
  name: herbal-gateway-service
  namespace: ds-assignment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: herbal-gateway-service
  template:
    metadata:
      labels:
        app: herbal-gateway-service
    spec:
      containers:
        - name: my-gateway
          image: stargazerdocker/herbal-docker-gateway-service:latest # replace with your Docker image name
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # replace with the port your app listens on

---

apiVersion: v1
kind: Service
metadata:
  name: herbal-gateway-service
  namespace: ds-assignment
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: herbal-gateway-service
